// Package glogr implements k8s.io/spartakus/pkg/logr.Logger in terms of
// github.com/golang/glog.
package glogr

// TODO: a clean way for apps to set the --vmodule flag
// TODO: a clean way for apps to set the --log_backtrace_at flag

import (
	"flag"
	"fmt"
	"runtime"
	"strconv"

	"github.com/golang/glog"
	"k8s.io/spartakus/pkg/logr"
)

// New returns a logr.Logger which is implemented by glog.
//
// Because glog only offers global logging functions (as opposed to logger
// objects), this will set some global parameters.  For example, if you call
// this more than once with different v arguments, the global verbosty level
// will change for all instances.
//
// Because glog does not offer an option to log to an arbitrary output, this
// forces logging to go to stderr.
func New(v int) (logr.Logger, error) {
	// Force logging to stderr.
	stderrFlag := flag.Lookup("logtostderr")
	if stderrFlag == nil {
		return nil, fmt.Errorf("can't find flag 'logtostderr'")
	}
	stderrFlag.Value.Set("true")

	// Set the V level.
	vFlag := flag.Lookup("v")
	if vFlag == nil {
		return nil, fmt.Errorf("can't find flag 'v'")
	}
	vFlag.Value.Set(strconv.Itoa(v))

	return glogger{
		level:  0,
		prefix: "",
	}, nil
}

type glogger struct {
	level  int
	prefix string
}

func prepend(prefix interface{}, args []interface{}) []interface{} {
	return append([]interface{}{prefix}, args...)
}

// Magic string for intermediate frames that we should ignore.
const autogeneratedFrameName = "<autogenerated>"

// Discover how many frames we need to climb to find the caller. This approach
// was suggested by Ian Lance Taylor of the Go team, so it *should* be safe
// enough (famous last words).
func framesToCaller() int {
	// 1 is the immediate caller.  3 should be too many.
	for i := 1; i < 3; i++ {
		_, file, _, _ := runtime.Caller(i + 1) // +1 for this function's frame
		if file != autogeneratedFrameName {
			return i
		}
	}
	return 1 // something went wrong, this is safe
}

func (l glogger) Info(args ...interface{}) {
	glog.InfoDepth(framesToCaller(), prepend(l.prefix, args)...)
}

func (l glogger) Infof(format string, args ...interface{}) {
	glog.InfoDepth(framesToCaller(), fmt.Sprintf("%s"+format, prepend(l.prefix, args)...))
}

func (l glogger) Enabled() bool {
	return bool(glog.V(glog.Level(l.level)))
}

func (l glogger) Error(args ...interface{}) {
	glog.ErrorDepth(framesToCaller(), prepend(l.prefix, args)...)
}

func (l glogger) Errorf(format string, args ...interface{}) {
	glog.ErrorDepth(framesToCaller(), fmt.Sprintf("%s"+format, prepend(l.prefix, args)...))
}

func (l glogger) V(level int) logr.InfoLogger {
	return glogger{
		level:  level,
		prefix: l.prefix,
	}
}

func (l glogger) NewWithPrefix(prefix string) logr.Logger {
	return glogger{
		level:  l.level,
		prefix: prefix,
	}
}

var _ logr.Logger = glogger{}
var _ logr.InfoLogger = glogger{}
